name: amplify_grocery_list
description: Grocery List to show AWS Amplify

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.2
  google_fonts: ^3.0.1
  # Flutter relies on the version 1.16.0 for collection
  collection: ^1.16.0
  amplify_flutter: ^1.0.0-next.1
  amplify_auth_cognito: ^1.0.0-next.1
  amplify_authenticator: ^1.0.0-next.1
  amplify_api: ^1.0.0-next.1
  amplify_storage_s3: ^1.0.0-next.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true